name: Tests

on:
  pull_request:
  push:
    branches: [master]

jobs:
  Pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - { os: ubuntu-22.04, py: "3.7", arch: x64 }
          - { os: ubuntu-22.04, py: "3.8", arch: x64 }
          - { os: ubuntu-22.04, py: "3.9", arch: x64 }
          - { os: ubuntu-22.04, py: "3.10", arch: x64 }
          - { os: ubuntu-22.04, py: "3.11", arch: x64 }
          - { os: ubuntu-22.04, py: "3.12", arch: x64 }
          - { os: ubuntu-22.04, py: "3.13", arch: x64 }
          - { os: macos-13, py: "3.7", arch: x64 }
          - { os: macos-13, py: "3.8", arch: x64 }
          - { os: macos-13, py: "3.9", arch: x64 }
          - { os: macos-13, py: "3.10", arch: x64 }
          - { os: macos-13, py: "3.11", arch: x64 }
          - { os: macos-13, py: "3.12", arch: x64 }
          - { os: macos-13, py: "3.13", arch: x64 }
          - { os: macos-latest, py: "3.8", arch: arm64 }
          - { os: macos-latest, py: "3.9", arch: arm64 }
          - { os: macos-latest, py: "3.10", arch: arm64 }
          - { os: macos-latest, py: "3.11", arch: arm64 }
          - { os: macos-latest, py: "3.12", arch: arm64 }
          - { os: macos-latest, py: "3.13", arch: arm64 }
          - { os: windows-latest, py: "3.7", arch: x64 }
          - { os: windows-latest, py: "3.8", arch: x64 }
          - { os: windows-latest, py: "3.9", arch: x64 }
          - { os: windows-latest, py: "3.10", arch: x64 }
          - { os: windows-latest, py: "3.11", arch: x64 }
          - { os: windows-latest, py: "3.12", arch: x64 }
          - { os: windows-latest, py: "3.13", arch: x64 }

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}
          architecture: ${{ matrix.arch }}
      - name: Install dependencies
        run: |
          pip install pytest
          pip install --upgrade pip
          gcc --version
          pip install -e . --verbose

      - name: Test with Pytest on Python ${{ matrix.py }}, ${{ matrix.platform }} ${{ matrix.arch }}
        run: python -m pytest